version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: "pip"
    directory: "/backend"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    allow:
      - dependency-type: production
    open-pull-requests-limit: 3