version: '3'

services:
  httpd:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - "5000:5000"
    links:
      - backend
      - frontend
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "5050:80"
    volumes:
      - ./backend:/app
    entrypoint:
      - "python"
      - "-m"
      - "app"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/app
    ports:
      - "5100:80"
