version: '3'

services:
  httpd:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - "5000:5000"
    links:
      - backend
      - frontend
    restart: always
  frontend:
    image: stardustdl/movie2comic:frontend
    restart: always
  backend:
    image: stardustdl/movie2comic:backend
    restart: always