version: '3'

services:
  httpd:
    image: abiosoft/caddy
    volumes:
      - ./Caddyfile:/etc/Caddyfile
    ports:
      - "5000:5000"
    links:
      - backend
      - frontend
    restart: always
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend.dev
    ports:
      - "5050:5050"
    volumes:
      - ./backend:/app
    entrypoint:
      - "python"
      - "-m"
      - "app"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "5100:5000"
